# -*- coding: utf-8 -*-
"""PDFmerger.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17UmoRRK3KHsEVAFYlht1cec8qKcuZfBU
"""

!pip install PyPDF2

from PyPDF2 import PdfMerger

# List of uploaded PDF files for merging
pdf_files = [
    "your pdf's path"  # Please set up here
    "your pdf's path"  # Please set up here
    "your pdf's path"  # Please set up here
]

# Output file path for the final merged PDF
final_pdf_path = "created pdf's path"  # Please set up here

# Merge PDFs
merger = PdfMerger()
for pdf in pdf_files:
    merger.append(pdf)

# Save the merged PDF
merger.write(final_pdf_path)
merger.close()

# Provide the path to the final merged file
final_pdf_path



