# -*- coding: utf-8 -*-
"""classifyCancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f1X_NCtgvqy3WBkKDLk_e_DkV5t6qtJ0
"""

import codecademylib3_seaborn
from sklearn.datasets import load_breast_cancer

# Explore the data
breast_cancer_data = load_breast_cancer()

# See the dataset
# print(breast_cancer_data.data[0])
# print(breast_cancer_data.feature_names)

# See the target variable
# print(breast_cancer_data.target)
# print(breast_cancer_data.target_names)

# Splitting the data into Training and Validation Sets
from sklearn.model_selection import train_test_split

training_data, validation_data, training_labels, validation_labels = train_test_split(breast_cancer_data.data, breast_cancer_data.target, test_size=0.2, random_state=100)
# print(training_data.shape)      # (455, 30)
# print(validation_data.shape)    # (114, 30)
# print(training_labels.shape)    # (455,)
# print(validation_labels.shape)  # (114,)


# Running the classifier
from sklearn.neighbors import KNeighborsClassifier

# Make a model
classifier = KNeighborsClassifier(n_neighbors = 3)
# Train the model
classifier.fit(training_data, training_labels)
# Test the model (Print out the score)
score = classifier.score(validation_data, validation_labels)
# print(score) # 0.947

# Try k from 1 to 100.
scores = []
for k in range(1, 101):
  classifier = KNeighborsClassifier(n_neighbors = k)
  classifier.fit(training_data, training_labels)
  score = classifier.score(validation_data, validation_labels)
  scores.append(score)

# Print out the maximum accurate result and its the number of k
max_score = max(scores)
print("max_score: ", max_score)
max_index = scores.index(max_score)
print("k: ", max_index)

# Graphing the results
import matplotlib.pyplot as plt
x = list(range(1, 101))
y = scores
plt.plot(x, y)
plt.title("Breast Cancer Classifier Accuracy")
plt.xlabel("K")
plt.ylabel("Validation Accuracy")
plt.show()