# -*- coding: utf-8 -*-
"""Activity6_Modules_and_Classes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m3aBVr4iqzLt22_J-mJ7cJBV30lPvCww

# Modules and Classes
## Exercise one
Write a module that provides the following conversions:

Length - feet (') and inches ('') to meters (m)
Mass - pounds (lbs) to kilograms (kg)
Temperature - Kelvin (K) to Celsius (oC)
Time - hours (h) and minutes(m) to seconds (s)
Each calculation should be within its own function, with the module, so you will write eight functions altogether. Write a program that provides a suitable menu system for your conversion functions. This program should import the module and access the functions (functions should not be defined in the same file as the user interface). You will need to carefully consider how the user enters information and the upper and lower bounds (valid range) for each type of conversion. For example, the temperature cannot go below 0o Kelvin.
"""

# Length Conversion: Feet and inches to meters
def feet_inches_to_meters(feet, inches):
    total_inches = feet * 12 + inches
    meters = total_inches * 0.0254
    return meters

# Length Conversion: Pounds to kilograms
def pounds_to_kilograms(pounds):
    return pounds * 0.453592

# Temperature Convversion: Kelvin to Celsius
def kelvin_to_celsius(kelvin):
    if kelvin < 0:
        raise ValueError("Temperature cannot be below 0 Kelvin")
    return kelvin - 273.15

# Time Conversion: Hours and minutes to seconds
def hours_minutes_to_seconds(hours, minutes):
    return hours * 3600 + minutes * 60

"""# EOF"""