# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d3D181gXa9IN6Bbf3JwEzGCaWo4PbTBr
"""

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from sklearn import linear_model

# Read df
df = pd.read_csv("https://content.codecademy.com/programs/data-science-path/linear_regression/honeyproduction.csv")

print(df.head())

# Group by year and total production (mean)
prod_per_year = df.groupby("year").totalprod.mean().reset_index()
print(prod_per_year)

# Make variables
X = prod_per_year["year"]
X = X.values.reshape(-1, 1)
print(X)
y = prod_per_year["totalprod"]
print(y)

# See the relationship between year and total production
plt.scatter(X, y)
plt.title("Plot Year and Total Production")
plt.xlabel("Year")
plt.ylabel("Total Production")
plt.show()

# Make a model
regr = linear_model.LinearRegression()
regr.fit(X, y)

# Print out slope and intercept
print(regr.coef_[0])
print(regr.intercept_)

# Predict total production (y) using Year (X)
y_predicted = regr.predict(X)
print(y_predicted)

# Show the line using X and Predicted y.
plt.plot(X, y_predicted, "r")
plt.show()

# Predict the Honey Decline
X_future = np.array(range(2013, 2051))
X_future = X_future.reshape(-1,1)
print(X_future)

# Predict future and Store predicted data
future_predict = regr.predict(X_future)
print(future_predict)

plt.plot(X_future, future_predict, "y")
plt.title("Future Pridiction")
plt.xlabel("Year")
plt.ylabel("Total Production")
plt.show()

# EOF

